### ISSUE TITLE
documentation not so clear as to how to use the services 

### ISSUE THREAD

**Issue by kpapag** [EOSC-synergy/FAIR_eva#44]
Hi everyone,

I would like some guidelines as to how can i run this service correctly. I have successfully cloned this repo and started both fair.py and web.py using latest python 3.10, running on windows.

web.py interface is always in Spanish language even if i switch to English. Every combination i test of an oai pmh endpoint always produces an error that i cant seem to understand.

Also, how can i structure an API call towards fair.py listening at  http://127.0.0.1:9090 ? Is it a get or a post request? Should the call include a body as well?

Thank you in advance!

**Comment by PalomoIFCA** [comment]
Hello:

Once you have the API waiting you can call it with something like  `curl -X POST "http://localhost:9090/v1.0/rda/rda_all" -H  "accept: application/json" -H  "Content-Type: application/json" -d '{"id":"http://hdl.handle.net/10261/157765","lang":"es","oai_base": "http://digital.csic.es/dspace-oai/request","repo":"oai-pmh"}'` You can also check alll the options if you open your browser and go to http://localhost:9090/v1.0/ui/ to see the Swagger UI
,

**Comment by PalomoIFCA** [comment]
Hello again.

There is a mistake in your curl, the oai_base link is not correct 

You should use https://datacatalogue.sodanet.gr/oai 

I used this one in the command line and it worked perfectly.

curl -X POST "http://localhost:9090/v1.0/rda/rda_all" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"id\":\"10.17903/FK2/0B2LM0\",\"lang\":\"en\",\"oai_base\":\"https://datacatalogue.sodanet.gr/oai\",\"repo\":\"oai-pmh\"}"
