### ISSUE TITLE
Docstring does not match with class attributes

### ISSUE THREAD

**Issue by bencomp** [EOSC-synergy/FAIR_eva#45]
It looks like the docstring for the `Digital_CSIC` class belongs to a different class completely:

https://github.com/EOSC-synergy/FAIR_eva/blob/fc4e59ff6962aa0456efcc99c6dd06d7149043c1/api/digital_csic.py#L19-L41

Perhaps you could replace it? The same goes for other subclasses of `Evaluator`.

**Comment by PalomoIFCA** [comment]
It has been replaced in the last merge

Thanks for your input
